### PR TITLE
fix: copy buffer view when iterating on file

### LINKED ISSUE #8: fetching local file returns a scrambled output
Hello!

When I try to load a JSON file using `file://` protocol content seems to get scrambled 😕 

Here's a link to [JSON file](https://gist.githubusercontent.com/lowlighter/2a1ae6f97860508c35eb9d6f3f58f78c/raw/9010db2df7df31b93964314303c38c52323ce752/overworld.gracidea.json) and below is a snippet which show that parsing with `Deno.readTextFile` is fine while using `fetch` output starts at line 4076 out of 4231 (which explains why it can't be parsed)
```ts
import { fetch } from "https://deno.land/x/file_fetch/mod.ts"
console.log(Deno.inspect(JSON.parse(await Deno.readTextFile("overworld.gracidea.json")), {depth:1}))
console.log("=======================")
console.log((await fetch(new URL("overworld.gracidea.json", import.meta.url)).then(res => res.text())).substring(0, 200))
console.log("=======================")
console.log(await fetch(new URL("overworld.gracidea.json", import.meta.url)).then(res => res.json()))
```

```
PS> deno run --allow-read test.ts
{ pins: [Object], areas: [Array], chunks: [Object] }
=======================
     "id": 215,
      "name": "3-safari-g-se",
      "points": [
        715,
        -1147,
        715,
        -1150,
        719,
        -1152,
        720,
        -1152,
        720,
        -1
=======================
error: Uncaught (in promise) SyntaxError: Unexpected token : in JSON at position 9
console.log(await fetch(new URL("overworld.gracidea.json", import.meta.url)).then(res => res.json()))
            ^
    at JSON.parse (<anonymous>)
    at packageData (deno:op_crates/fetch/22_body.js:247:21)
    at Response.json (deno:op_crates/fetch/22_body.js:192:18)
```

Any ideas?
Like https://github.com/denoland/deno/issues/2150#issuecomment-830667424 mentioned, this lib is used on deno deploy so it's probably broken on it too

___

Edit: After more digging I think it's from deno's implementation of `Response` itself that the problem occurs. It is possible actually possible to reconstruct original string using directly `TextDecoder` and string. Tested both with `Deno.iter` and `iter` from std.

```ts
const file = await Deno.open(new URL("overworld.gracidea.json", import.meta.url), { read: true })
const original = await Deno.readTextFile("overworld.gracidea.json")
let copy = ""
const body = new ReadableStream<Uint8Array>({
  start: async (controller) => {
    for await (const chunk of Deno.iter(file)) {
      copy += new TextDecoder().decode(chunk)
    }
    file.close();
    controller.close();
  },
  cancel() {
    file.close();
  },
});
console.log((await new Response(body, {status: 200}).text()).substring(0, 200))
console.log(copy === original) //Output "true"
console.log(Deno.inspect(JSON.parse(copy), {depth:1})) //Output "{ pins: [Object], areas: [Array], chunks: [Object] }"
```

### PR DESCRIPTION
**Pull request by lowlighter**
Closes #8

As @lucacasonato debugged in https://github.com/denoland/deno/issues/10467, scrambled response output on large files may occur because the buffer is not copied so its content may change between iterations

Unless it has changed, this module is used by *deno deploy* and thus causing problems on it when trying to load large local files (current workaround was to use raw.githubusercontent instead of fetching local files) 

It requires the patch for `- writable: true` from #9 to work, I left it out to avoid conflicts with it 👍

### CODE REVIEW

**Comment by lowlighter** [comment]
Seems that [`Default size of the buffer is 32kB.`](https://deno.land/std@0.97.0/io/util.ts#L202), but added text file only weight 3kb so test probably doesn't cover fix. Should I duplicate it 11 times more ?

**Comment by lucacasonato** [comment]
Yeah please - or just generate a file into /tmp during the test.

**Comment by lowlighter** [comment]
Let me know when #9 gets merged so I can rebase on it to make build successful 👍

**Comment by lucacasonato** [comment]
Merged :-)

**Comment by lowlighter** [comment]
Should work now 🙂

**Review by lucacasonato — APPROVED** [review]
LGTM. Thanks :-)

**Comment by lowlighter** [comment]
Thanks a lot! 
It may need a new release so [denoland/deployctl](https://github.com/denoland/deployctl) can be [patched](https://github.com/denoland/deployctl/blob/main/src/runtime.js#L7) too

My memory is a bit fuzzy about whether it only impacted deployctl or deno deploy too but if the later also uses this polyfill it may also need to be updated

**Comment by lucacasonato** [comment]
released 0.2.0 now. Deno Deploy does not use this polyfill.

**Pull request merged**
